### ISSUE TITLE
Bilder in der Lightbox auflisten

### ISSUE THREAD

**Issue by Schmidty2** [BugBuster1701/contao-dlstats-bundle#24]
Hallo,
kann die Option hinzugefügt werden, dass die Bilder, die einer Lightbox geöffnet werden, in einer separaten Liste gezählt und im Backend aufgelistet werden (analog den Datei-Downloads).

Use case: Eine Fotografenhomepage mit themenbezogenen Fotogalerien auf verschiedenen Seiten. Der Fotograf möchte gerne wissen, welche Fotos aus der Fotogalerie groß und wie oft in der Lightbox angezeigt werden (und damit für den Homepagebesucher interessant sind).

Eine finanzielle Unterstütung ist möglich.

**Comment by BugBuster1701** [comment]
Nein, das hat nichts mit dem Download Hook zu tun auf dem die Downloadstatistik basiert.
Dazu wären andere Tool besser geeignet.
